[build]
target = "riscv32imc-esp-espidf"

[target.riscv32imc-esp-espidf]
linker = "ldproxy"
rustflags = [
	"--cfg", "espidf_time64",
	"-C", "default-linker-libraries"
]

[unstable]
build-std = ["std", "panic_abort"]

[env]
ESP_IDF_TOOLS_INSTALL_DIR = { value = "global" }
ESP_IDF_VERSION = "v5.1.1"
